import AppKit

@MainActor
protocol PasteboardPrivacy {
    func requireReadable(_ pasteboard: NSPasteboard) throws
}

struct SystemPasteboardPrivacy: PasteboardPrivacy {
    func requireReadable(_ pasteboard: NSPasteboard) throws {
        Timing.event("pasteboardAccessBehavior", count: pasteboard.accessBehavior.rawValue)
        guard pasteboard.accessBehavior != .alwaysDeny else { throw AppFailure.clipboardDenied }
    }
}

struct ClipboardSnapshot {
    struct Item { var representations: [(NSPasteboard.PasteboardType, Data)] }
    var items: [Item]
}

@MainActor
final class PasteboardSession {
    static let markers = ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
                          "org.nspasteboard.AutoGeneratedType"].map { NSPasteboard.PasteboardType($0) }
    private let board: NSPasteboard
    private let privacy: any PasteboardPrivacy
    private let snapshot: ClipboardSnapshot
    private(set) var expectedCount: Int
    private var ownsChanges = false
    private var finished = false

    init(board: NSPasteboard = .general, privacy: any PasteboardPrivacy = SystemPasteboardPrivacy()) throws {
        self.board = board
        self.privacy = privacy
        try privacy.requireReadable(board)
        let before = board.changeCount
        // A nil result can be denial, not an empty clipboard. Never clear an
        // unreadable original by treating it as an empty snapshot.
        guard let originals = board.pasteboardItems else { throw AppFailure.clipboardUnreadable }
        var items: [ClipboardSnapshot.Item] = []
        for item in originals {
            var representations: [(NSPasteboard.PasteboardType, Data)] = []
            for type in item.types {
                // Full fidelity takes precedence over proceeding with a partial snapshot.
                guard let data = item.data(forType: type) else {
                    try privacy.requireReadable(board)
                    throw AppFailure.clipboardUnreadable
                }
                representations.append((type, data))
            }
            guard !representations.isEmpty else { throw AppFailure.clipboardUnreadable }
            items.append(.init(representations: representations))
        }
        try privacy.requireReadable(board)
        guard before == board.changeCount else { throw AppFailure.clipboardChanged }
        snapshot = ClipboardSnapshot(items: items)
        expectedCount = before
    }

    func requireUnchanged() throws {
        guard board.changeCount == expectedCount else { throw AppFailure.clipboardChanged }
    }

    @discardableResult
    func recordCopyChange() -> Bool {
        guard board.changeCount != expectedCount else { return false }
        expectedCount = board.changeCount
        ownsChanges = true
        return true
    }

    func acceptCopy() throws -> String {
        try requireUnchanged()
        try privacy.requireReadable(board)
        guard let text = board.string(forType: .string) else {
            try privacy.requireReadable(board)
            throw AppFailure.noText
        }
        let types = board.types ?? []
        let html = types.contains(.html) ? board.data(forType: .html) : nil
        let rtf = types.contains(.rtf) ? board.data(forType: .rtf) : nil
        try privacy.requireReadable(board)
        guard board.changeCount == expectedCount else { throw AppFailure.clipboardChanged }
        guard !(types.contains(.html) && html == nil), !(types.contains(.rtf) && rtf == nil) else {
            throw AppFailure.clipboardUnreadable
        }
        guard !SelectionStructure.requiresCellNavigation(text: text, html: html, rtf: rtf) else {
            throw AppFailure.tableSelection
        }
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { throw AppFailure.noText }
        return text
    }

    func writePayload(_ payload: String) throws -> PastePayloadProvider {
        try requireUnchanged()
        try privacy.requireReadable(board)
        let provider = PastePayloadProvider(payload)
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.string])
        for type in Self.markers { item.setData(Data(), forType: type) }
        expectedCount = board.clearContents()
        ownsChanges = true
        let success = board.writeObjects([item])
        expectedCount = board.changeCount
        guard success else { throw AppFailure.clipboardWrite }
        return provider
    }

    enum RestoreResult: Equatable { case restored, untouched, newerClipboardKept }

    @discardableResult
    func restore() throws -> RestoreResult {
        guard !finished else { return .untouched }
        finished = true
        guard ownsChanges else { return .untouched }
        guard board.changeCount == expectedCount else { return .newerClipboardKept }
        let items = snapshot.items.map { saved in
            let item = NSPasteboardItem()
            for (type, data) in saved.representations { item.setData(data, forType: type) }
            return item
        }
        board.clearContents()
        if !items.isEmpty && !board.writeObjects(items) { throw AppFailure.clipboardRestore }
        return .restored
    }
}

// AppKit may request promised data from another thread. This object contains
// only immutable payload bytes and a lock-protected signal; no actor hops.
final class PastePayloadProvider: NSObject, NSPasteboardItemDataProvider, @unchecked Sendable {
    private let bytes: Data
    private let lock = NSLock()
    private var requested = false
    init(_ payload: String) { bytes = Data(payload.utf8) }
    var wasRequested: Bool { lock.withLock { requested } }
    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        item.setData(bytes, forType: type)
        lock.withLock { requested = true }
    }
}
